---
nav:
    - Home: index.md
    - Installation: installation/index.md
    - How to Use:
          - 1. Create a Django project: how-to-use/start-project.md
          - 2. Create a Component: how-to-use/create-component.md
          - 3. Reference your Component: how-to-use/reference-component.md
          - 4. Render your Component: how-to-use/render-component.md
          - 5. Learn More: how-to-use/learn-more.md
    - Django-Only Features:
          - Hooks: django/hooks.md
          - Template Tag: django/templatetag.md
    - Contribute:
          - Django-IDOM Environment: contribute/idom-env.md
          - Documentation Environment: contribute/docs-env.md
          - Running Tests: contribute/running-tests.md
    - Changelog: changelog/index.md

theme:
    name: material
    palette:
        - scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: deep-orange
          accent: deep-orange
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: deep-orange
          accent: deep-orange
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - toc.integrate
        - navigation.top

    icon:
        repo: fontawesome/brands/github

markdown_extensions:
    - toc:
          permalink: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - admonition
    - attr_list

plugins:
    - search
    - include-markdown
    - git-revision-date-localized:
          fallback_to_build_date: true

site_name: Django IDOM Docs
site_author: Archmonger
site_description: React for Django developers.
repo_url: https://github.com/idom-team/django-idom
site_url: https://idom-team.github.io/django-idom
repo_name: idom-team/django-idom
edit_uri: edit/docs
